sfera.o: sfera.h sfera.C
	g++ -c sfera.C

sol_Es_10_1.o: sol_Es_10_1.C
	g++ -c sol_Es_10_1.C

sol_Es_10_1.x: sol_Es_10_1.o sfera.o
	g++ sol_Es_10_1.o sfera.o -o sol_Es_10_1.x

sol_Es_10_2.o: sol_Es_10_2.C
	g++ -c sol_Es_10_2.C

sol_Es_10_2.x: sol_Es_10_2.o sfera.o
	g++ sol_Es_10_2.o sfera.o -o sol_Es_10_2.x

sol_Es_10_3.o: sol_Es_10_3.C
	g++ -c sol_Es_10_3.C

sol_Es_10_3.x: sol_Es_10_3.o sfera.o
	g++ sol_Es_10_3.o sfera.o -o sol_Es_10_3.x

sol_Es_10_4.o: sol_Es_10_4.C
	g++ -c sol_Es_10_4.C

sol_Es_10_4.x: sol_Es_10_4.o sfera.o
	g++ sol_Es_10_4.o sfera.o -o sol_Es_10_4.x